// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CommentReplyController from "./comment_reply_controller"
application.register("comment-reply", CommentReplyController)

import PreviewsController from "./previews_controller"
application.register("previews", PreviewsController)

import TiptapController from "./tiptap_controller"
application.register("tiptap", TiptapController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
